Admin log view
space-wizards/SS14.Admin pull request #5
Opened 2022-04-05 22:47 UTC by juliangiebel

First version of the admin log view.
I will keep working on this but I'm opening a PR so I can get a review before I add more stuff and so it can be used already.

The links in the details pane will point to overview pages for the server/round/player when I implement them.

I'm not a designer so if I would appreciate suggestions on how to make this look and feel better.

Fulltextsearch doesn't work right now because the index isn't being used properly but that needs to be fixed in content.

### Screenshots:
![grafik](https://user-images.githubusercontent.com/8915246/161863318-8b4315af-f0d4-44aa-b8df-28fbe554103c.png)
![grafik](https://user-images.githubusercontent.com/8915246/161863342-f95dbb7a-a153-4c8f-9564-c530e09632d5.png)

2022-04-06 15:18 UTC, PJB3005 commented
VERY based

2022-04-30 22:10 UTC, DrSmugleaf requested changes

2022-04-30 22:10 UTC, DrSmugleaf commented on SS14.Admin/Pages/Logs/Index.cshtml.cs
> +            if (FromDate != DateTime.MaxValue) AllRouteData.Add("toDate", ToDate.ToString("yyyy-MM-dd"));
```suggestion
            if (FromDate != default) AllRouteData.Add("fromDate", FromDate.ToString("yyyy-MM-dd"));
            if (ToDate != default) AllRouteData.Add("toDate", ToDate.ToString("yyyy-MM-dd"));
```

2022-04-30 22:32 UTC, DrSmugleaf requested changes

2022-04-30 22:32 UTC, DrSmugleaf commented on SS14.Admin/AdminLogs/LogJsonTagHelper.cs
> +    private string ParsePositon(JsonProperty property)
```suggestion
            "coordinates" => ParsePosition(entry),
            "position" => ParsePosition(entry),
            _ => default
        };

        return result != default;
    }

    private async Task<string> TranslateProperty(JsonProperty property) => property.Name switch
    {
        "player" => await RetrievePlayerLink(property),
        _ => $"<p>{property.Name}: {property.Value.GetRawText() ?? "NULL"}</p>"
    };

    private string ParsePosition(JsonProperty property)

```

2022-04-30 22:32 UTC, DrSmugleaf commented on SS14.Admin/Pages/Logs/Index.cshtml.cs
> +            //.ThenInclude(player => player.Player)
Are these supposed to be included?

2022-04-30 22:52 UTC, PJB3005 commented on SS14.Admin/Models/JsonQueryBinder.cs
> +                Console.WriteLine(e);
Probably don't want to keep this console writeline.

2022-05-01 14:44 UTC, juliangiebel commented on SS14.Admin/Pages/Logs/Index.cshtml.cs
> +            //.ThenInclude(player => player.Player)
No. I removed the comments.

2022-05-01 14:45 UTC, juliangiebel commented on SS14.Admin/Pages/Logs/Index.cshtml.cs
> +            if (FromDate != DateTime.MaxValue) AllRouteData.Add("toDate", ToDate.ToString("yyyy-MM-dd"));
I changed FromDate to ToDate on line 38

2022-05-03 20:36 UTC, merged